### ISSUE TITLE
Document hamming distance

### ISSUE THREAD

**Issue by pallix** [TattdCodeMonkey/crc#14]
Hello,

According to this [paper](https://users.ece.cmu.edu/~koopman/networks/dsn02/dsn02_koopman.pdf), it is possible to detect errors with a longer hamming distance with CRC-32 by using other polynomial than the usual one.

Do the implementation use the suggestion of the paper?

Where can I find a documentation of hamming distance errors for the various CRC implemented?

Would it make sense to add that to the README?

**Comment by pallix** [comment]
This [PDF document](https://users.ece.cmu.edu/~koopman/pubs/koopman14_crc_faa_conference_presentation.pdf) (2014) documents the optimal polynomials.

**Comment by TattdCodeMonkey** [comment]
@pallix There is actually a refactor in place that should be landing in the near future that will allow calculating CRC with any set of custom variables for: 
- initial value
- polynomial
- final xor value
- input reflected
- result reflected

That work is discussed in #13 and currently under the `single` branch.

I'm not familiar with the hamming distance errors your referencing, I would likely need to read the paper linked to get an idea on what to add here in reference to that. So unfortunately I don't have good answers to your questions.
