### ISSUE TITLE
Argument error when encoding a large binary

### ISSUE THREAD

**Issue by pallix** [TattdCodeMonkey/crc#17]
I get `** (ArgumentError) argument error`  when computing the CRC of a binary constituted of 34599 bytes with `CRC.ccitt_16`

Is it to be expected??

**Comment by TattdCodeMonkey** [comment]
It is not. we have [some tests](https://github.com/TattdCodeMonkey/crc/blob/master/test/crc_test.exs#L12) explicitly testing 40,961 byte inputs. let me add one for `CRC.ccitt_16/1`and see if I can reproduce locally.

**Comment by TattdCodeMonkey** [comment]
@pallix I see the same thing locally, [reproduced with a test](https://github.com/TattdCodeMonkey/crc/blob/ccitt_16_arg_error_on_large_input/test/crc_16_test.exs#L33-L36). Thanks for reporting this. I will try to resolve soon.

**Comment by pallix** [comment]
Thank you for the quick feedback.

**Comment by TattdCodeMonkey** [comment]
@pallix this should be resolved in `v0.8.0` Note the `CRC.ccitt16/1` & `CRC.ccitt16/2` now use the underlying `:crc_fast.calc` which can be used directly if need be. Documentation for the new generic crc function will be written at some point when I get some time to address it 😬
