### ISSUE TITLE
Can't start application in directory with spaces in name

### ISSUE THREAD

**Issue by aliksend** [TattdCodeMonkey/crc#26]

**Comment by TattdCodeMonkey** [comment]
Can you elaborate?

**Comment by aliksend** [comment]
Steps to reproduce
```bash
cd ~/Documents
mix new crc_test
mv crc_test 'crc test'
cd 'crc test'
nano mix.exs # add dep
mix deps.get
mix deps.compile
```
and got 
```
==> crc
Makefile:149: target `/Users/aliksend/Documents/crc' given more than once in the same rule.
Makefile:173: warning: overriding commands for target `/Users/aliksend/Documents/crc'
Makefile:150: warning: ignoring old commands for target `/Users/aliksend/Documents/crc'
 LD     crc_nif.so
clang: error: no such file or directory: 'test/deps/crc/c_src/test/deps/crc/priv/crc_nif.so'
make: *** [test/deps/crc/c_src/test/deps/crc/priv/crc_nif.so] Error 1
could not compile dependency :crc, "mix compile" failed. You can recompile this dependency with "mix deps.compile crc", update it with "mix deps.update crc" or clean it with "mix deps.clean crc"
==> crc_test
** (Mix) Could not compile with "make" (exit status: 2).
You need to have gcc and make installed. Try running the
commands "gcc --version" and / or "make --version". If these programs
are not installed, you will be prompted to install them.
```
Of course I have both make and gcc installed.
To fix that just
```bash
cd ..
mv 'crc test' crc_test
cd crc_test
mix deps.compile
```
and got
```
==> crc
 C      checksum_xor.c
 C      crc_8.c
 C      crc_algorithm.c
 C      crc_model.c
 C      crc_nif.c
 C      crc_resource.c
 C      xnif_slice.c
 LD     crc_nif.so
Compiling 7 files (.erl)
Compiling 3 files (.ex)
Generated crc app
```

**Comment by TattdCodeMonkey** [comment]
@aliksend Thanks! I'll take a look when I get a chance, but it'll likely be next week with the US holiday this weekend.

**Comment by aliksend** [comment]
@TattdCodeMonkey ok, not a problem. Thanks for reply.

**Comment by TattdCodeMonkey** [comment]
So this is basically an issues with the [Makefile](https://github.com/TattdCodeMonkey/crc/blob/master/c_src/Makefile#L3-L4) we use `shell pwd` to set an argument for the current dir. To support spaces in the project name that variable would need spaces escaped with `\ `. But the general consensus from doing searching is `make` [does not support pathnames containing whitespace](https://stackoverflow.com/questions/17965806/how-do-i-handle-files-with-spaces-in-my-makefile). So given that I don't see much value fixing an issue that isn't supported by the underlying tooling.

**Comment by aliksend** [comment]
You can also wrap pathname in `'` to fix that, or I'm not right?

**Comment by TattdCodeMonkey** [comment]
The directory is used as a variable inside the makefile. Whenever a path is used in the makefile the final command would need the computed path wrapped in `'`s. Which ends up not being straightforward given how often the directory variables are used.

**Comment by aliksend** [comment]
Yes, it can require a lot of boilerplate work, but it will fix issue with spaces in project pathname.
