### ISSUE TITLE
Nif module not found when running tests

### ISSUE THREAD

**Issue by lasseebert** [TattdCodeMonkey/crc#34]
Lately I get a lot of this kind of error when running my tests locally:

```
** (UndefinedFunctionError) function :crc_nif.crc_fast/2 is undefined (module :crc_nif is not available)
```

When re-running with e.g. `mix test --failed`, the same tests are green and nothing have been compiled since the error.

I'm not sure if this belongs here. Perhaps it is an issue of elixir_make, elixir or erlang.
I recently updated to erlang 23.0, and I think this is where the problems started.

I have no similar problems on the CI server (that also runs tests) or in my production or staging environments. I'm also not able to reproduce the error. It just comes some times - I see it perhaps around 2-3 times per 8 hour working day.

Has anyone seen something similar or know what might be wrong?

I'm running:
* crc 0.10.0
* elixir_make 0.6.0
* elixir 1.10.3
* erlang 23.0.1
* Ubuntu

**Comment by lasseebert** [comment]
Update: I have now also seen the same behaviour on the CI server (Github actions) when running tests. Doing a re-run will make it green again (at least in all cases so far). We cache the deps and _build folders on the CI and the re-run does not recompile any dependencies.

**Comment by lasseebert** [comment]
This is perhaps related to https://github.com/actions/setup-elixir/issues/30#issuecomment-642774179.
It seems that crc [is using](https://github.com/TattdCodeMonkey/crc/blob/268153c07507121af94b5cd3b89c5dc57feda2ac/c_src/Makefile#L106) [the deprecated](https://www.erlang.org/news/140) `-lerl_interface`.

**Comment by TattdCodeMonkey** [comment]
@lasseebert #35 might resolve this issue. I just released [0.10.1](https://hex.pm/packages/crc/0.10.1) to include this change.

**Comment by lasseebert** [comment]
@TattdCodeMonkey Yes that seems like it will fix my issue. I will test it asap and report back.

**Comment by lasseebert** [comment]
@TattdCodeMonkey This seems to solve my issue. Closing issue. If the problem comes again, I'll report back here. (The problem only came some times)

Thanks @TattdCodeMonkey and @fhunleth :tada:

**Comment by lasseebert** [comment]
I was a little too fast. I got this error again during test:

```
** (UndefinedFunctionError) function :crc_nif.crc_fast/2 is undefined (module :crc_nif is not available)
```

Rerunning the test made it green without recompilation.
The good thing is that I don't need `erlang-dev` anymore to be able to compile crc, which was solved by #35.

**Comment by TattdCodeMonkey** [comment]
@lasseebert dang :(

I'll setup a test project and see if I can reproduce and discern any root causes. Let me know learn anything else.

**Comment by lasseebert** [comment]
I am able to periodically reproduce it in my own project. If it fails and I rerun the tests with the same seed it will fail around 1 in 5 times.

I have tried to reproduce inside the crc project's test suite, but have not been able to do it.

This makes me think that something in my own project is at fault.
I will continue to investigate.

**Comment by lasseebert** [comment]
I am able to (periodically) reproduce in a small project now.

I have set up this small example repo: https://github.com/lasseebert/crc_nif_error
It has `crc` as dep and I added two tests.

I am still not completely sure what is going on.

I have made these observations:

* When I start the test with `Code.ensure_loaded(:crc_nif)`, I can not reproduce the error
* When the test is not `async: true`, I can not reproduce the error.
* I can not reproduce the error within the crc repo test suite

I now get more output (because in my project, we use another Logger backend in test env, which is not printing to console):

```
01:35:48.759 [warn]  The on_load function for module crc_nif returned:
{:badarg, [{:erlang, :load_nif, [:erlang, :apply], []}, {:crc_nif, :init, 0, [file: 'src/crc_nif.erl', line: 104]}, {:code_server, :"-handle_on_load/5-fun-0-", 1, [file: 'code_server.erl', ...]}]}


01:35:48.761 [error] Process #PID<0.205.0> raised an exception
** (ArgumentError) argument error
    :erlang.load_nif(:erlang, :apply)
    (crc 0.10.1) src/crc_nif.erl:104: :crc_nif.init/0
    (kernel 7.0) code_server.erl:1355: anonymous fn/1 in :code_server.handle_on_load/5


  1) test test 3 (ATest)
     test/a_test.exs:12
     ** (UndefinedFunctionError) function :crc_nif.crc_fast/2 is undefined or private
     code: CRC.crc(:crc_16_xmodem, <<1, 2, 3, 4, 5, 4, 3, 2, 1>>)
     stacktrace:
       (crc 0.10.1) :crc_nif.crc_fast(:crc_16_xmodem, <<1, 2, 3, 4, 5, 4, 3, 2, 1>>)
       test/a_test.exs:13: (test)

.......

Finished in 0.08 seconds
1 doctest, 7 tests, 1 failure

Randomized with seed 468259
```

To reproduce, I use this (fish syntax - will not work in e.g. bash):

```
➤ while mix test --seed 468259
  end
```

And then wait for an error. Will typically come within the first 10 runs, at least on my computer.

**Comment by TattdCodeMonkey** [comment]
🤔 I wonder if adding`Code.ensure_loaded(:crc_nif)` to CRC module would resolve this then. It probably couldn’t hurt.

**Comment by lasseebert** [comment]
I suspect more and more that this is a race condition that happens on module loading in Elixir or Erlang, and that it has nothing to do with crc or ex_unit. And perhaps the race condition happens because of the `init` callback on load in `crc_nif` because it takes an amount of time to finish.

**Comment by lasseebert** [comment]
And since this started after I upgraded to Erlang 23, that is where I will try to look.

**Comment by lasseebert** [comment]
This seems to be the issue: https://bugs.erlang.org/browse/ERL-1273
A fix has already been merged: https://github.com/erlang/otp/pull/2649

I will test with the proposed fix.

**Comment by lasseebert** [comment]
I have tested with the [`maint` branch](https://github.com/erlang/otp/tree/maint) of OTP (to which the fix was merged), and I can no longer reproduce the issue :tada: 

I'm guessing this will be out in OTP 23.0.3, which is the next patch version.

Thanks for the help and your time with this :)
