### ISSUE TITLE
Incorrect Value compared to python binascii crc32?

### ISSUE THREAD

**Issue by avinayak** [TattdCodeMonkey/crc#48]
In python3,

```python
>>> from binascii import crc32
>>> crc32(b"123", 34) # Provide an initial value
3011637596
```

In elixir using this library:
```elixir
iex(36)> CRC.crc(%{extend: :crc_32, init: 34}, "123")
2297841019
```
Is this a bug?

**Comment by TattdCodeMonkey** [comment]
I'm not sure if `b"123"` and `"123"` are equivalent so your not doing an apples to apples comparison is my guess.

I tested the elixir input you showed here: http://www.sunshine2k.de/coding/javascript/crc/crc_js.html and got the same result that the library gives:
![image](https://github.com/TattdCodeMonkey/crc/assets/1972968/df24bdc0-a4e5-4056-9733-7c0c09bee0ae)

Result CRC value: 0x88F6457B === 2297841019
